# Generated by Django 4.1 on 2023-12-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_boards_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='workspace',
            field=models.CharField(max_length=100),
        ),
    ]
