# Generated by Django 4.1 on 2023-12-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_card_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
    ]
