# Generated by Django 4.1 on 2023-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
