# Generated by Django 4.1 on 2023-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_assignee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
