# Generated by Django 4.1 on 2023-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_assignee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='slug',
            field=models.SlugField(default='12', unique=True),
        ),
        migrations.AlterField(
            model_name='boards',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='columns',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
