# Generated by Django 4.1 on 2023-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_boards_slug_alter_boards_name_alter_columns_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
