# Generated by Django 4.1 on 2023-12-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_boards_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
