# Generated by Django 4.1 on 2023-12-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_card_assignee_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignee',
            old_name='card_id',
            new_name='card',
        ),
    ]
