# Generated by Django 4.1 on 2023-12-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_rename_card_id_assignee_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='max_members',
            field=models.IntegerField(default='1'),
        ),
    ]
