# Generated by Django 4.1 on 2023-12-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='card',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
    ]
