# Generated by Django 4.1 on 2023-12-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_rename_card_comments_card_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='card_id',
            new_name='card',
        ),
    ]
