# Generated by Django 4.1 on 2023-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_rename_card_id_comments_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
