# Generated by Django 4.1 on 2023-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_comments_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('workspace', models.CharField(max_length=255)),
                ('organizer_id', models.CharField(max_length=255)),
                ('starting_time', models.CharField(max_length=40)),
                ('expiration_time', models.CharField(max_length=2400)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='assignee',
            unique_together={('user', 'card')},
        ),
    ]
