# Generated by Django 4.1 on 2023-12-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_meeting_alter_assignee_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
